"""
OpenFang Pipelines — Deployed automation scripts.

Each pipeline is a Python module with a standard entry point:
    async def run(context: PipelineContext) -> PipelineResult

Pipelines are generated by the Codification Engine and
executed by the Pipeline Executor on cron schedules.
"""
